version: '3.8'
services:

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 15432:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: postgres
    hostname: postgres
    user: root

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: nestjs@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin:
  