version: '3.8'
services:
  app:
    build:
      context: ./Dockerfiles
      dockerfile: app.Dockerfile
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - postgres
  postgres:
    build:
      context: ./Dockerfiles
      dockerfile: db.Dockerfile
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: postgres
    hostname: postgres
    user: root
  pgadmin:
    build:
      context: ./Dockerfiles
      dockerfile: pgadmin.Dockerfile
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: nestjs@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  pgdata:
  pgadmin:
  